name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://fw-sci.s3.us-west.stackpathstorage.com/firmware/SS-G950USQS5CRL1-to-U5DRL7-UP?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=3VAY3IFBH85E8981GF21%2F20210120%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210120T040902Z&X-Amz-Expires=86400&X-Amz-Signature=faf87fcab7adf1000eba28093a74c8a068d2654e375808e01e7a08e762075765&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22firmware-science-G950USQS5CRL1-to-G950USQU5DRL7.zip%22
  ROM_NAME: OneUI
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to BitSend
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof final/GSI.zip

         
            
